sudo: false

language: node_js
node_js:
  - "10"
cache: npm

install:
  - npm install

script:
  - npm test
  - npm run build

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
    export REPO=rhizomik/usocial;
    export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`;
    docker build -f packages/client/Dockerfile -t $REPO:$TRAVIS_COMMIT packages/client;
    docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG;
    docker push $REPO;
    export REPO=rhizomik/usocial-api;
    docker build -f packages/api/Dockerfile -t $REPO:$TRAVIS_COMMIT packages/api;
    docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG;
    docker push $REPO;
    fi